### ISSUE TITLE
Remove non-authoritative assets

### ISSUE THREAD

**Issue by flaviut** [nim-lang/assets#3]
The things in `Unused/` and `Experimental/` are unused and might confuse someone visiting the repo.

It may be a good idea to delete them from master / move them to another branch.

Ref #2.

**Comment by dom96** [comment]
Perhaps, or we simply need an "Official" and "Unofficial" folder, and a readme explaining clearly the difference between the two.

**Comment by flaviut** [comment]
Fixed in 399a75c7cdfcafad50ee9691309b14c63c285571
