### ISSUE TITLE
FEATURE REQUESTS: Website / Documentation

### ISSUE THREAD

**Issue by aniljava** [nim-lang/assets#4]
For example, after visiting a page such as :

http://nim-lang.org/docs/threads.html

The only way back to its parent (The Standard Library) is pressing a back button. Can we have a shared header across all generated pages with may be a navigation trail or atleast to the navigation root.

My apologies if this is not the right place to make such suggestions.

**Comment by flaviut** [comment]
I've been out of the loop with Nim for a while, but I believe that this belongs in the [nim-lang/Nim](https://github.com/nim-lang/Nim/) bug tracker. There's also a lot more people watching that repo.

This repo is just a place to keep all the logo stuff.

**Comment by dom96** [comment]
Yeah, please report in nim-lang/nim repo.
