### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by dom96** [nim-lang/assets#5]
We have this: https://github.com/nim-lang/assets/blob/master/Art/README.md

But could we decide on a license and stick it in the repo?

cc @Araq @flaviut

**Comment by flaviut** [comment]
The logo was created by @PhilipWitte so he's really the person to ask. Maybe the IRC logs would offer some hints into how he intended to licence the art.

**Comment by PhilipWitte** [comment]
The logo I made is copyrighted to Araq and/or the Nim team. License is up to you. If there's some kind of paperwork we need to sign to make that official, let me know.

**Comment by dom96** [comment]
Brilliant. In that case we need to figure out what license to give this.

@Araq any ideas?

**Comment by Araq** [comment]
Nope. Need to look into artist licenses.

**Comment by dom96** [comment]
https://creativecommons.org/choose/

**Comment by flaviut** [comment]
This was fixed in 399a75c7cdfcafad50ee9691309b14c63c285571
